server {
  listen 5000;
  listen [::]:5000;

  access_log /var/log/nginx/hemengyang.tk.log combined;

  root /app/typecho;
  index index.php;

  # 开启伪静态化
  if (!-e $request_filename) {
    rewrite ^(.*)$ /index.php$1 last;
  }

  # 禁止对数据库的访问
  location ~ .*\.db$ {
    return 403;
  }

  location ~ .*\.php(\/.*)*$ {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;

    fastcgi_pass php:9000;
    fastcgi_index $document_root/index.php;

    # 缓冲区
    fastcgi_buffers 4 64k;
    fastcgi_buffer_size 64k;

    # 上传附件
    client_max_body_size 50m;
    client_body_buffer_size 50m;

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
    fastcgi_param PATH_INFO $fastcgi_path_info;
  }

  location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
    expires 30d;
    add_header Vary Accept-Encoding;
    access_log off;
  }

}
