upstream django {
    server smart-home:8000;
}

server {
  listen 5001;
  listen [::]:5001;

  access_log /var/log/nginx/smart.hemengyang.tk.log combined;

  root /app/smart-home/web;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~ ^/(graphql|admin|xiaoai) {
    uwsgi_pass  django;
    include  uwsgi_params;
  }

  location /static {
    alias /app/smart-home/static;
  }
}
