version: "3"
services:
  nginx:
    build: ./nginx
    image: he0119/nginx:1.19.4-alpine
    container_name: nginx
    labels:
      - sh.acme.autoload.domain=hehome.xyz
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./blog/typecho:/app/typecho
      - ./smart-home/static:/app/smart-home/static
      - ./smart-home/web:/app/smart-home/web
      - ./smart-home/assetlinks.json:/app/smart-home/web/.well-known/assetlinks.json
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
      - smart-home
    networks:
      default:
        ipv4_address: 172.20.0.255
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    restart: always
    command: daemon
    volumes:
      - ./acme.sh/acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=hehome.xyz
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE="/etc/nginx/ssl/hehome.xyz.key"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/fullchain.cer"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="nginx -s reload"
    depends_on:
      - nginx
  php:
    build: ./blog/php
    image: he0119/php:7.4.12-fpm-alpine
    container_name: php
    user: 1000:1000
    restart: always
    volumes:
      - ./blog/typecho:/app/typecho
      - ./blog/php/php.ini:/usr/local/etc/php/php.ini:ro
  smart-home:
    image: he0119/smart-home:v0.7.2
    container_name: smart-home
    restart: always
    user: 1000:1000
    volumes:
      - ./smart-home/static:/usr/src/app/static
      - ./smart-home/logs:/usr/src/app/logs
    env_file:
      - ./.env
    depends_on:
      - db
      - emqx
      - redis
  celery:
    image: he0119/smart-home:v0.7.2
    command: celery -A home worker --beat -l info
    container_name: celery
    restart: always
    user: 1000:1000
    volumes:
      - ./smart-home/logs:/usr/src/app/logs
    env_file:
      - ./.env
    depends_on:
      - redis
  db:
    build: ./postgres
    image: he0119/postgres:12.3
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    restart: always
  emqx:
    image: emqx/emqx:4.2.5-alpine-amd64
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
    env_file:
      - ./emqx/configuration.env
      - ./.env
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
        - subnet: fd00::/80
